---
title: "Transformations fig: v2"
author: "Lauren Hsu"
date: "6/18/2021"
output: 
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include = F, eval = F}
setwd('reproduce_figs/')
```

```{r, message = F}
library(SingleCellExperiment)
library(corral)
try(source('../R/load_pkgs.R'))
try(source('../R/utils.R'))
try(source('../R/plotting_utils.R'))
try(source('../R/glmpca_feat_selection.R'))
```


Setting the directory for where plots will be saved
```{r, message = F}
# plot_dir is the directory where all the plots are saved
# save_dir is where to read the data from



plot_dir <- '../figs_50pcss/'
save_dir <- '../data/0_make_all_transformations_data_50pcs/'

checkdir(plot_dir)
```

## loading data 

created by: 

- 01_make_all_transformations_data
- 02_clust_ARI_transformations_data

```{r}
# reading in data from 0_make_all_transformations_data

scelist <- readRDS(file = paste0(save_dir, 'scelist.rds'))
decomp_list <- readRDS(file = paste0(save_dir, 'decomp_list.rds'))
emb_list <- readRDS(file = paste0(save_dir, 'emb_list.rds'))

# reading in ctlist from 02_clust_ARI_transformations_data

ctlist <- readRDS(file = paste0(save_dir, 'ctlist.rds'))

clust_lists <- list('nngraph' = readRDS(file = paste0(save_dir, 'nngraph_clust.rds')))

# clust_lists <- list('nngraph' = readRDS(file = paste0(save_dir, 'nngraph_clust.rds')),
#                     'louvain' = readRDS(file = paste0(save_dir, 'louvain_clust.rds')))

```


## 5. time plots

```{r}
glmpca_times <- lapply(decomp_list, FUN = function(dl) dl[['glmpca']]$runtime)
ca_times <- lapply(decomp_list, FUN = function(dl) dl[['CA']]$runtime)
time_df <- data.frame(dataset = c(names(glmpca_times), names(ca_times)),
                      rbind(Reduce(rbind, glmpca_times), Reduce(rbind,ca_times)),
                      method = c(rep('glmpca', length(glmpca_times)), 
                                 rep('CA', length(ca_times))))
time_df$ncells <- unlist(lapply(scelist, ncol)[time_df$dataset])

time_df$runtime_min <- time_df$user.self/60

time_gg <- ggplot(time_df, aes(x = ncells, y = runtime_min, color = method)) + 
  geom_point() + theme_classic() + scale_color_manual(values = mthcolors) 

savegg2pdf(time_gg, 'time_comp', wdim = 5, hdim = 5)
```



## 2. ARI

```{r}
ARI_df_allclusts <- data.frame()
for(cmth in names(clust_lists)){
  ARIs <- lapply(clust_lists[[cmth]], '[[','ARI_df')
  ARI_df <- Reduce(rbind, ARIs)
  ARI_df <- cbind(ARI_df, cmethod = rep(cmth, nrow(ARI_df)))
  ARI_df_allclusts <- rbind(ARI_df_allclusts, ARI_df)
}

# code for taking the avg or median of ARI across multiple glmpca seed instances
collapse_glmpca <- function(df){
  res <- data.frame()
  for(n in unique(df$npc)){
    for(cm in unique(df$cmethod)){
      for(dat in unique(df$dataset)){
        inds <- intersect(which(df$npc == n), which(df$cmethod == cm))
        inds <- intersect(inds, which(df$dataset == dat))
        tres <- data.frame(ARI = aggfun(df$ARI[inds]),
                           method = 'glmpca',
                           npc = n,
                           dataset = dat,
                           cmethod = cm,
                           ARI_sd = sqrt(var(df$ARI[inds])), 
                           ARI_med = median(df$ARI[inds]),
                           ARI_avg = mean(df$ARI[inds]))
        res <- rbind(tres, res)
      }
    }
  }
  return(res)
}

cres <- collapse_glmpca(ARI_df_allclusts)

ARI_df_gsumm <- rbind(ARI_df_allclusts,  cres[,1:5])


```

### ARI heatmap

```{r}
best_per_mth <- function(df){
  mths <- as.list(unique(df$method))
  bymth <- lapply(mths, function(x) df[which(df$method == x),])
  ARIs <- lapply(bymth, function(x) x[which(x$ARI == max(x$ARI))[1],])
  Reduce(rbind, ARIs)
}

ARI_df <- Reduce(rbind, lapply(clust_lists$nngraph, '[[','ARI_df'))

# ARI_df$method[grep('glmpca',ARI_df$method)] <- 'glmpca'

summed_ARI <- Reduce(rbind, lapply(as.list(unique(ARI_df$dataset)), FUN = function(datname) best_per_mth(ARI_df[which(ARI_df$dataset == datname),])))

datnames <- c("zhengmix4eq" = 'Zhengmix4eq',
              "zhengmix4uneq" = 'Zhengmix4uneq', 
              "zhengmix8eq" = 'Zhengmix8eq',
              'baron_panc' = 'Pancreas: Baron',
              'lawlor_panc' = 'Pancreas: Lawlor',
              'muraro_panc' = 'Pancreas: Muraro',
              'chen_brain' = 'Brain: Chen',
              'darmanis_brain' = 'Brain: Darmanis',
              'xenopus' = 'Aztekin xenopus tail')

# remapping the dataset name column
summed_ARI$dataset_name <- datnames[summed_ARI$dataset]

ari_gg <- ggplot(data = summed_ARI, aes(x = method, y = dataset_name, fill = ARI)) + 
  geom_tile() + 
  scale_fill_viridis_b(breaks = seq(0, 1, .15)) + 
  # alt: scale_fill_viridis_b(breaks = seq(0, 1, .2)) + 
  geom_text(aes(label = round(ARI, 2))) + 
  theme(axis.text.x = element_text(angle = 90)) + 
  scale_x_discrete(labels = mthnames)

ari_gg

```


```{r}
mths_keep <- c('std','ftalt_p',
               'varstab','anscombe_std','ft_x_std','deflate',
               'glmpca')

dat_order <- c('zhengmix4eq','zhengmix4uneq','zhengmix8eq',
               'baron_panc','muraro_panc','lawlor_panc',
               'chen_brain', 'darmanis_brain', 'xenopus')

summed_ARI_glmpca <- summed_ARI[grep('glmpca',summed_ARI$method),]
summed_ARI_glmpca_means <- data.frame(ARI = aggregate(summed_ARI_glmpca, 
                                                      list(dataset = summed_ARI_glmpca$dataset),
                                                      mean)[,2], 
                                      method = 'glmpca',
                                      npc = 0,
                                      dataset = aggregate(summed_ARI_glmpca, 
                                                          list(dataset = summed_ARI_glmpca$dataset),
                                                          mean)[,1])

summed_ARI_glmpca_means$dataset_name <-  datnames[summed_ARI_glmpca_means$dataset]

summed_ARI_gsumm <- rbind(summed_ARI[-grep('glmpca',summed_ARI$method),],
                          summed_ARI_glmpca_means)

ari_gg <- ggplot(data = summed_ARI_gsumm,
                 aes(y = method, x = dataset, fill = ARI)) + 
  geom_tile() + 
  scale_fill_viridis_b(breaks = seq(0, 1, .1)) + 
  # alt: scale_fill_viridis_b(breaks = seq(0, 1, .2)) + 
  geom_text(aes(label = round(ARI, 2))) + 
  theme(axis.text.x = element_text(angle = 90)) + 
  scale_y_discrete(labels = mthnames, limits = rev(mths_keep)) +
  scale_x_discrete(labels = datnames, position = 'top',guide = guide_axis(angle = 60),
                   limits = dat_order)

ari_gg

savegg2pdf(ari_gg, 'ARI_heatmap_nngraph_vF', wdim = 8, hdim = 5)

## plot to show glmpca variation by seed

ari_gg_glmpca <- ggplot(data = summed_ARI_glmpca,
                 aes(y = method, x = dataset, fill = ARI)) + 
  geom_tile() + 
  scale_fill_viridis_b(breaks = seq(0, 1, .1)) + 
  # alt: scale_fill_viridis_b(breaks = seq(0, 1, .2)) + 
  geom_text(aes(label = round(ARI, 2))) + 
  theme(axis.text.x = element_text(angle = 90)) + 
  scale_x_discrete(labels = datnames, position = 'top',guide = guide_axis(angle = 45),
                   limits = dat_order)

ari_gg_glmpca

savegg2pdf(ari_gg_glmpca, 'ARI_heatmap_nngraph_glmpca', wdim = 8, hdim = 3)
```

### ARI line plots

```{r}
ari_dir <- paste0(plot_dir, 'ARIxPC_subset/')
checkdir(ari_dir)

# 1

nnclust_lists_sub1 <- clust_lists$nngraph

for(dat in names(nnclust_lists_sub1)){
  mthvec <- nnclust_lists_sub1[[dat]]$ARI_df$method
  ikeep <- unique(c(which(mthvec %in% mths_keep[-which(mths_keep == 'glmpca')]), 
                    grep('glmpca', mthvec)))
  nnclust_lists_sub1[[dat]]$ARI_df <- nnclust_lists_sub1[[dat]]$ARI_df[ikeep,]
}


# light gray #D4D4D4 light blue #B5E2FF
glmpca_colors <- rep('#D4D4D4', length(grep('glmpca',unique(ARIs$zhengmix4eq$method))))
names(glmpca_colors) <- grep('glmpca',unique(ARIs$zhengmix4eq$method), value = TRUE)

ARIs <- lapply(nnclust_lists_sub1, '[[','ARI_df')
ggobj <- plot_datfacetARI(Reduce(rbind, ARIs), plot_title = 'nngraph', dat_cols = c(mthcolors, glmpca_colors))
ggobj
savegg2pdf(ggobj, paste0('1_', 'nngraph'), dir = ari_dir)
```



